### ISSUE TITLE
"Coverage" cannot collect test class

### ISSUE THREAD

**Issue by TrailingDots** [aleph2c/miros#1]
I was interested in collecting test coverage for the miros code.

While running the test with  "coverage run -m pytest" I get the following:

<pre>
    miros/examples/single_unit_three_stage_charger_3_test.py:28
 /home/xxx/play/PyProjects/miros/miros/examples/single_unit_three_stage_charger_3_test.py:28:  PytestCollectionWarning: cannot collect test class 'TestOutputCsv' because it has a __init__ constructor (from: miros/examples/single_unit_three_stage_charger_3_test.py)
    class TestOutputCsv:
</pre>

The problem is solved at https://docs.pytest.org/en/latest/warnings.html 

     For example, pytest will emit a warning if it encounters a class that matches 
    python_classes but also defines an __init__ constructor, as this prevents the 
    class from being instantiated

The solution is to name the class at line 28, "TestOutputCsv" to something like "XTestOutputCsvX".
These two files need changing:

    miros/examples/single_unit_three_stage_charger_3_test.py
    miros/examples/single_unit_three_stage_charger_4_test.py

My configuration:

<pre>
Linux, Centos 7
python --version
Python 3.7.3
coverage --version
Coverage.py, version 4.5.3 with C extension
Documentation at https://coverage.readthedocs.io
pytest --version
This is pytest version 5.0.1, 
setuptools registered plugins:
  pytest-cov-2.7.1 
  pytest-httpbin-1.0.0 
</pre>

**Comment by aleph2c** [comment]
I adjusted the files as you requested.
