### ISSUE TITLE
class ThreadSafeAttribute from unit tests results in None for fdata.lines

### ISSUE THREAD

**Issue by TrailingDots** [aleph2c/miros#2]
When I ran unit tests under coverage, attempts to access the previous frame in class
ThreadSafeAttribute in method __get__ the call at line 42 returns fdata.lines as None.
The test is miros/test/thread_safe_attributes_test.py:536.
The problem is in miros/miros/thread_safe_atributes.py.

I have slightly modified the code starting at line 41 in miros/miros/thread_safe_atributes.py:

<pre>
    fdata = FrameData(*inspect.getframeinfo(previous_frame))
    previous_line = "FooBar"
    try:
        previous_line = fdata.lines[0]    # Original line
    except TypeError as err:
        print(f"fdata={fdata}: {err}")
        print(f"previous_frame: {previous_frame}")
        #raise
    if self.is_not_atomic(previous_line):
 </pre>

This "trace" reports:  (slightly edited)

<pre>
fdata=FrameData(filename='.../miros/test/thread_safe_attributes_test.py', 
line_number=270,  function_name='thread_runner', lines=None, index=None): 
'NoneType' object is not subscriptable
</pre>

This error gets repeated many times before reporting:

<pre>
Fatal Python error: could not acquire lock for <_io.BufferedWriter name='<stdout>'> 
at interpreter shutdown, possibly due to daemon threads
</pre>

Without the <code>previous_line = "FooBar"</code> the test would hang and I had to
kill it with ^C. This ^C reports:

<pre>
^CException ignored in: <module 'threading' from '/home/cecilm/anaconda3/envs/py37/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/home/cecilm/anaconda3/envs/py37/lib/python3.7/threading.py", line 1281, in _shutdown
    t.join()
  File "/home/cecilm/anaconda3/envs/py37/lib/python3.7/threading.py", line 1032, in join
    self._wait_for_tstate_lock()
  File "/home/cecilm/anaconda3/envs/py37/lib/python3.7/threading.py", line 1048, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
</pre>

Obviously the code is dead locked.

I downloaded the miros repo from github yesterday, Jan 23, 2020.

My configuration:

<pre>
python --version
Python 3.7.3
coverage --version
Coverage.py, version 4.5.3 with C extension
Documentation at https://coverage.readthedocs.io
pytest --version
This is pytest version 5.0.1, 
setuptools registered plugins:
  pytest-cov-2.7.1 
  pytest-httpbin-1.0.0 
</pre>

**Comment by TrailingDots** [comment]
Just realized the problems with print() in threaded code.

The original code produced the following and then hung. Had to kill with ^C  : 

<pre>
self = &lt;miros.thread_safe_attributes.ThreadSafeAttribute object at 0x7f3a72830080&gt;
instance = &lt;test.thread_safe_attributes_test.Example2 object at 0x7f3a703dbb38&gt;
owner = &lt;class 'test.thread_safe_attributes_test.Example2'&gt;

    def __get__(self, instance, owner):
      #print("get acquiring lock")
      self._lock.acquire(blocking=True)
      self._is_atomic = True
      previous_frame = inspect.currentframe().f_back
      fdata = FrameData(*inspect.getframeinfo(previous_frame))
>     previous_line = fdata.lines[0]
E     TypeError: 'NoneType' object is not subscriptable

miros/miros/thread_safe_attributes.py:42: TypeError
======================= 4 failed, 133 passed in 35.30 seconds ========================
</pre>

**Comment by aleph2c** [comment]
I haven't been using ``coverage``.  

Thank you for bringing it to my attention.  

I have installed it and gone through your reproduction steps but I am unable to reproduce your issue.  I am running a more modern version (5.0.3) of the ``coverage`` tool than you are, perhaps you could update your coverage library and the problem will go away.

As for running ``print`` in threaded code, the ``ActiveObject`` provides an API to a thread safe version of ``print``, see this [link](https://aleph2c.github.io/miros/recipes.html#thread-safe-printing-and-instrumentation) for details.

**Comment by TrailingDots** [comment]
Agreed. I updated my coverage and coverage works as expected.
I frequently wish python had better async possibilities.

Thanks for your prompt, courteous attention!   :))
