### ISSUE TITLE
a few more typos

### ISSUE THREAD

**Issue by vkalyvayut-roboty-a-ne-chelovek** [aleph2c/miros#8]
I'm sorry for rushing the previous issue.

1. skipped ** for the header [Link](https://aleph2c.github.io/miros/html/zero_to_one.html#zero-to-one-zero-to-one:~:text=queues%20in%20the-,diagram,-%3F**)

2. should be "there are" instead of "their are" I guess [Link](https://aleph2c.github.io/miros/html/zero_to_one.html#zero-to-one-zero-to-one:~:text=In%20this%20case%20their%20are%20two%20events%20pending%20in%20the%20queue)

3. instead of ```oven.list_spy```, there should be ```oven.live_spy``` [Link](https://aleph2c.github.io/miros/html/zero_to_one.html#zero-to-one-zero-to-one:~:text=oven.list_spy%20%3D%20True)

4. is ```owen.start_at(door_closed)``` missing before ```oven.post_fifo``` call? ```https://aleph2c.github.io/miros/html/zero_to_one.html#zero-to-one-zero-to-one:~:text=.spy())-,def%20spy_on_buzz()%3A%0A%20%20oven%20%3D%20ToasterOvenMock(name%3D%22oven%22),-%23%20Send%20the%20buzz```

5. should there be "toasting" instead of "toaster"? [Link](https://aleph2c.github.io/miros/html/zero_to_one.html#zero-to-one-zero-to-one:~:text=The%20toaster%20callback%E2%80%99s%20if%2Delif%20logical)

6. lines 256-260, 278-282 should be highlighted [Link](https://aleph2c.github.io/miros/html/zero_to_one.html#iter5-code)

7. lines 40-41 should be highlighted [Link](https://aleph2c.github.io/miros/html/zero_to_one.html#zero-to-one-zero-to-one:~:text=self.get_ready_sec%20%3D%20get_ready_sec)

8. the entire "buzz" method should be highlighted [Link](https://aleph2c.github.io/miros/html/zero_to_one.html#zero-to-one-zero-to-one:~:text=if%20self.live_spy%20%3D%3D%20False%3A)

9. the ```ToasterOvenMock(ToasterOven).__init__``` method should be highlighted too [Link](https://aleph2c.github.io/miros/html/zero_to_one.html#zero-to-one-zero-to-one:~:text=Event(signal%3Dsignals.Done%2C%20payload%3DBuzzSpec(buzz_times%3D2))%2C)

10. lines 322-323 should be highlighted [Link](https://aleph2c.github.io/miros/html/zero_to_one.html#zero-to-one-zero-to-one:~:text=oven.cook_time(oven.bake_time_in_sec))

**Comment by aleph2c** [comment]
Thank you for your contributions.
