### ISSUE TITLE
Add link to testing examples on Testing page

### ISSUE THREAD

**Issue by vkalyvayut-roboty-a-ne-chelovek** [aleph2c/miros#9]
I think it would be good to add links to [testing recipe](https://aleph2c.github.io/miros/html/recipes.html#testing) on [Testing page](https://aleph2c.github.io/miros/html/testing.html), because when I open Testing page and see nothing it is a bit disappointing.

**Comment by aleph2c** [comment]
Thank you for providing the link to the testing recipe, that made updating these docs much easier.

I was going to add documentation on how to integrate the python logger with the trace and spy using a logging.yml file.  I just haven't done it yet.

**Comment by aleph2c** [comment]
Updated
